/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
        // UniTitle: typeof import("@dcloudio/uni-ui/lib/uni-title/uni-title.vue")['default']
  }
}
