/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PubllcButton: typeof import('./components/publlc-button.vue')['default']
    PubllcComponentActivity: typeof import('./components/publlc-component-activity.vue')['default']
    PubllcInput: typeof import('./components/publlc-Input.vue')['default']
    PubllcProjectsComponent: typeof import('./components/publlc-projects-component.vue')['default']
  }
}
