/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/dynamic/dynamic" |
       "/pages/my/my" |
       "/pages/public-benefit/public-benefit" |
       "/pages/recommen-projects/recommen-projects" |
       "/pages/volunteer-activity/volunteer-activity" |
       "/pages/index/components/publlc-open" |
       "/pages/index/components/publlc-recommend";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/public-benefit/public-benefit" | "/pages/volunteer-activity/volunteer-activity" | "/pages/dynamic/dynamic" | "/pages/my/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
